### ISSUE TITLE
Tips/Suggestions

### ISSUE THREAD

**Issue by nexuspcs** [lucas-jb/easypass-generator#1]
Hello, 

Looking in your code, it seems that you use `random`. While this works fine, I would advise against it, as the `random` library in Python is not truly random.
Take a look at this article extract:

> The Birthday Paradox, or why PRNGs produce duplicates more often than you might think.
> 
> 
> There are a couple of issues at play in the OP's problem. One is the [birthday paradox](http://en.wikipedia.org/wiki/Birthday_problem) as mentioned above and the second is the nature of what you are generating, which does not inherently guarantee that a given number will not be repeated.
> 
> The Birthday Paradox applies where given value can occur more than once during the period of the generator - and therefore duplicates can happen within a sample of values. The effect of the Birthday Paradox is that the real likelihood of getting such duplicates is quite significant and the average period between them is smaller than one might otherwise have thought. This dissonance between the perceived and actual probabilities makes the Birthday Paradox a good example of a [cognitive bias](http://en.wikipedia.org/wiki/Cognitive_bias), where a naive intuitive estimate is likely to be wildly wrong.
> 
> A quick primer on Pseudo Random Number Generators (PRNGs)
> 
> The first part of your problem is that you are taking the exposed value of a random number generator and converting it to a much smaller number, so the space of possible values is reduced. Although some [pseudo-random number generators](http://en.wikipedia.org/wiki/Pseudorandom_number_generator) do not repeat values during their period this transformation changes the domain to a much smaller one. The smaller domain invalidates the 'no repeats' condition so you can expect a significant likelihood of repeats.
> 
> Some algorithms, such as the [linear congruential PRNG](http://en.wikipedia.org/wiki/Linear_congruential_generator) (A'=AX|M) do guarantee uniqueness for the entire period. In an LCG the generated value contains the entire state of the accumulator and no additional state is held. The generator is deterministic and cannot repeat a number within the period - any given accumulator value can imply only one possible successive value. Therefore, each value can only occur once within the period of the generator. However, the period of such a PRNG is relatively small - about 2^30 for typical implementations of the LCG algorithm - and cannot possibly be larger than the number of distinct values.
> 
> Not all PRNG algorithms share this characteristic; some can repeat a given value within the period. In the OP's problem, the [Mersenne Twister](http://en.wikipedia.org/wiki/Mersenne_twister) algorithm (used in Python's [random](http://docs.python.org/library/random.html) module) has a very long period - much greater than 2^32. Unlike a Linear Congruential PRNG, the result is not purely a function of the previous output value as the accumulator contains additional state. With 32-bit integer output and a period of ~2^19937, it cannot possibly provide a such a guarantee.
> 
> The Mersenne Twister is a popular algorithm for PRNGs because it has good statistical and geometric properties and a very long period - desirable characteristics for a PRNG used on simulation models.
> 
> Good [statistical properties](http://en.wikipedia.org/wiki/Uniform_distribution_(discrete)) mean that the numbers generated by the algorithm are evenly distributed with no numbers having a significantly higher probability of appearing than others. Poor statistical properties could produce unwanted skew in the results.
> Good [geometric properies](http://random.mat.sbg.ac.at/~charly/server/node3.html) mean that sets of N numbers do not lie on a hyperplane in N-dimensional space. Poor geometric properties can generate spurious correlations in a simulation model and distort the results.
> A long period means that you can generate a lot of numbers before the sequence wraps around to the start. If a model needs a large number of iterations or has to be run from several seeds then the 2^30 or so discrete numbers available from a typical LCG implementation may not be sufficient. The MT19337 algorithm has a very long period - 2^19337-1, or about 10^5821. By comparison, the total number of atoms in the universe is estimated at about 10^80.
> The 32-bit integer produced by an MT19337 PRNG cannot possibly represent enough discrete values to avoid repeating during such a large period. In this case, duplicate values are likely to occur and inevitable with a large enough sample.
> 
> The Birthday Paradox in a nutshell
> 
> This problem is originally defined as the probability of any two people in the room sharing the same birthday. The key point is that any two people in the room could share a birthday. People tend to naively misinterpret the problem as the probability of someone in the room sharing a birthday with a specific individual, which is the source of the [cognitive bias](http://en.wikipedia.org/wiki/Cognitive_bias) that often causes people to underestimate the probability. This is the incorrect assumption - there is no requirement for the match to be to a specific individual and any two individuals could match.
> 
> This graph shows the probability of a shared birthday as the number of people in the room increases.  For 23 people the probability of two sharing a birthday is just over 50%.
> 
> The probability of a match occurring between any two individuals is much higher than the probability of a match to a specific individual as the match does not have to be to a specific date. Rather, you only have to find two individuals that share the same birthday. From this graph (which can be found on the Wikipedia page on the subject), we can see that we only need 23 people in the room for there to be a 50% chance of finding two that match in this way.
> 
> From the [Wikipedia entry on the subject](http://en.wikipedia.org/wiki/Birthday_problem) we can get a [nice summary.](http://en.wikipedia.org/wiki/Birthday_problem#Understanding_the_problem) In the OP's problem, we have 4,500 possible 'birthdays', rather than 365. For a given number of random values generated (equating to 'people') we want to know the probability of any two identical values appearing within the sequence.
> 
> Computing the likely effect of the Birthday Paradox on the OP's problem
> 
> For a sequence of 100 numbers, we have (100 * 99) / 2 = 4950 pairs (see [Understanding the Problem](http://en.wikipedia.org/wiki/Birthday_problem#Understanding_the_problem)) that could potentially match (i.e. the first could match with the second, third etc., the second could match the third, fourth etc. and so on), so the number of combinations that could potentially match is rather more than just 100.
> 
> From [Calculating the Probability](http://en.wikipedia.org/wiki/Birthday_problem#Calculating_the_probability) we get an expression of 1 - (4500! / (4500**100 * (4500 - 100)!) . The following snippet of Python code below does a naive evaluation of the probability of a matching pair occurring.
> ```python
> # === birthday.py ===========================================
> #
> from math import log10, factorial
> 
> PV=4500          # Number of possible values
> SS=100           # Sample size
> 
> # These intermediate results are exceedingly large numbers;
> # Python automatically starts using bignums behind the scenes.
> #
> numerator = factorial (PV)          
> denominator = (PV ** SS) * factorial (PV - SS)
> 
> # Now we need to get from bignums to floats without intermediate
> # values too large to cast into a double.  Taking the logs and 
> # subtracting them is equivalent to division.
> #  
> log_prob_no_pair = log10 (numerator) - log10 (denominator)
> 
> # We've just calculated the log of the probability that *NO*
> # two matching pairs occur in the sample.  The probability
> # of at least one collision is 1.0 - the probability that no 
> # matching pairs exist.
> #
> print 1.0 - (10 ** log_prob_no_pair)
> ```
> This produces a sensible looking result of p=0.669 for a match occurring within 100 numbers sampled from a population of 4500 possible values. (Maybe someone could verify this and post a comment if it's wrong). From this we can see that the lengths of runs between matching numbers observed by the OP seem to be quite reasonable.
> 
> Footnote: using shuffling to get a unique sequence of pseudo-random numbers
> 
> See [this answer below from S. Mark](https://stackoverflow.com/questions/2145510/python-random-is-barely-random-at-all/2145533#2145533) for a means of getting a guaranteed unique set of random numbers. The technique the poster refers to takes an array of numbers (which you supply, so you can make them unique) and shuffles them into a random order. Drawing the numbers in sequence from the shuffled array will give you a sequence of pseudo-random numbers that are guaranteed not to repeat.
> 
> Footnote: Cryptographically Secure PRNGs
> 
> The MT algorithm is not [cryptographically secure](http://en.wikipedia.org/wiki/Cryptographically_secure_pseudorandom_number_generator) as it is relatively easy to infer the internal state of the generator by observing a sequence of numbers. Other algorithms such as [Blum Blum Shub](http://en.wikipedia.org/wiki/Blum_Blum_Shub) are used for cryptographic applications but may be unsuitable for simulation or general random number applications. Cryptographically secure PRNGs may be expensive (perhaps requiring bignum calculations) or may not have good geometric properties. In the case of this type of algorithm, the primary requirement is that it should be computationally infeasible to infer the internal state of the generator by observing a sequence of values.
>

**Comment by nexuspcs** [comment]
Here is the [StackOverflow link](https://stackoverflow.com/a/2145551)

**Comment by lucasjuarezb** [comment]
Thanks for the contribution @nexuspcs! Even knowing that the random library is not really random, I think it adapts well to the intentions of the code. Anyway, if you have any suggestions I'm open to accept a pull request!

**Comment by nexuspcs** [comment]
Alright, that makes sense,
